AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation
Resources:
    S3Bucket:
        Type: 'AWS::S3::Bucket'
        Properties:
            AccessControl: PublicRead
            WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: error.html
        DeletionPolicy: Retain
        Metadata:
            'AWS::CloudFormation::Designer':
                id: fd35610d-6d3e-49b1-8666-94d6d3babfe5
    BucketPolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
            PolicyDocument:
                Id: MyPolicy
                Version: 2012-10-17
                Statement:
                    - Sid: PublicReadForGetBucketObjects
                      Effect: Allow
                      Principal: '*'
                      Action: 's3:GetObject'
                      Resource: !Join
                          - ''
                          - - 'arn:aws:s3:::'
                            - !Ref S3Bucket
                            - /*
            Bucket: !Ref S3Bucket
        Metadata:
            'AWS::CloudFormation::Designer':
                id: 345b6099-3427-4f4e-8d64-7aa820cd2495
    SQSQ4OSYH:
        Type: 'AWS::SQS::Queue'
        Properties: {}
        Metadata:
            'AWS::CloudFormation::Designer':
                id: d344ac44-609c-44ec-a23f-a9383063727a
Outputs:
    WebsiteURL:
        Value: !GetAtt
            - S3Bucket
            - WebsiteURL
        Description: URL for website hosted on S3
    S3BucketSecureURL:
        Value: !Join
            - ''
            - - 'https://'
              - !GetAtt
                  - S3Bucket
                  - DomainName
        Description: lauribucket